import requests
import time

BASE_URL = "http://localhost:3000"
TIMEOUT = 30

def test_verify_real_time_notifications_system():
    session = requests.Session()
    try:
        # 1. Authenticate user (assuming anesthesiologist user)
        auth_resp = session.post(
            f"{BASE_URL}/api/auth/login",
            json={"email": "testuser@example.com", "password": "TestPassword123!"},
            timeout=TIMEOUT
        )
        assert auth_resp.status_code == 200, "Authentication failed"
        auth_data = auth_resp.json()
        access_token = auth_data.get("access_token") or auth_data.get("token")
        assert access_token, "No access token received"

        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json"
        }

        # 2. Trigger a notification via backend API (simulate an event that generates notification)
        # Assuming there's an API to create a notification for testing purposes
        notif_payload = {
            "type": "alert",
            "title": "Test Alert Notification",
            "message": "This is a test real-time alert generated by automated test.",
            "user_role": "anesthesiologist"
        }
        create_notif_resp = session.post(
            f"{BASE_URL}/api/notifications",
            headers=headers,
            json=notif_payload,
            timeout=TIMEOUT
        )
        assert create_notif_resp.status_code == 201, "Notification creation failed"
        notif_data = create_notif_resp.json()
        notif_id = notif_data.get("id")
        assert notif_id, "Notification ID not returned"

        # 3. Fetch notifications list and verify the new notification appears
        notifications_resp = session.get(
            f"{BASE_URL}/api/notifications",
            headers=headers,
            timeout=TIMEOUT
        )
        assert notifications_resp.status_code == 200, "Failed to fetch notifications"
        notifications = notifications_resp.json()
        assert any(n["id"] == notif_id for n in notifications), "New notification not found in list"

        # 4. Validate the notification content
        notif_in_list = next(n for n in notifications if n["id"] == notif_id)
        assert notif_in_list["title"] == notif_payload["title"], "Notification title mismatch"
        assert notif_in_list["message"] == notif_payload["message"], "Notification message mismatch"
        assert notif_in_list["type"] == notif_payload["type"], "Notification type mismatch"
        assert notif_in_list["read"] is False or notif_in_list["read"] == 0, "Notification should be unread initially"

        # 5. Mark notification as read
        mark_read_resp = session.put(
            f"{BASE_URL}/api/notifications/{notif_id}/read",
            headers=headers,
            timeout=TIMEOUT
        )
        assert mark_read_resp.status_code == 200, "Failed to mark notification as read"
        updated_notif = mark_read_resp.json()
        assert updated_notif.get("read") is True or updated_notif.get("read") == 1, "Notification read status not updated"

        # 6. Simulate real-time delivery by polling notifications endpoint for new alerts
        # (Simulate waiting for real-time event; here we just check the created notification)
        polling_attempts = 3
        found_real_time = False
        for _ in range(polling_attempts):
            poll_resp = session.get(
                f"{BASE_URL}/api/notifications",
                headers=headers,
                timeout=TIMEOUT
            )
            assert poll_resp.status_code == 200, "Polling notifications failed"
            poll_data = poll_resp.json()
            if any(n["id"] == notif_id for n in poll_data):
                found_real_time = True
                break
            time.sleep(1)
        assert found_real_time, "Notification not delivered in real-time simulation"

    finally:
        # Cleanup: delete the notification
        try:
            if 'notif_id' in locals():
                del_resp = session.delete(
                    f"{BASE_URL}/api/notifications/{notif_id}",
                    headers=headers,
                    timeout=TIMEOUT
                )
                assert del_resp.status_code == 200 or del_resp.status_code == 204, "Failed to delete notification"
        except Exception:
            pass

test_verify_real_time_notifications_system()
